site_name: Haro's Blogs
site_author: https://www.facebook.com/duchao3003/
theme:
  name: material
  features:
    - content.footnote.tooltips

docs_dir: ./docs

plugins:
  - search
  - glightbox

use_directory_urls: false

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js